name: Podman Build and Scan

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Podman
        run: |
          sudo apt update
          sudo apt install -y podman
          podman --version
          podman info

      - name: Build Podman Image
        run: |
          podman build -t localhost/python-podman-app:latest .

      - name: Verify Image Exists
        run: |
          podman images

  scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install Podman
        run: |
          sudo apt update
          sudo apt install -y podman
          podman --version

      - name: Install Trivy
        run: |
          wget -qO- https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo tee /etc/apt/trusted.gpg.d/trivy.asc
          echo "deb https://aquasecurity.github.io/trivy-repo/deb jammy main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt update
          sudo apt install -y trivy
          trivy --version

      - name: Scan Podman Image with Trivy
        run: |
          podman pull localhost/python-podman-app:latest
          trivy image --input localhost/python-podman-app:latest

   




