name: Build and Scan Podman Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Podman
        run: |
          sudo apt update
          sudo apt install -y podman

      - name: Build Podman Image
        run: |
          podman build -t python-podman-app:latest .

    scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install Podman
        run: |
          sudo apt update
          sudo apt install -y podman

      - name: Install Trivy
        run: |
          wget -qO- https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo tee /etc/apt/trusted.gpg.d/trivy.asc
          echo "deb https://aquasecurity.github.io/trivy-repo/deb jammy main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt update
          sudo apt install -y trivy

      - name: Scan Podman Image with Trivy
        run: |
          trivy image python-podman-app:latest





        

