name: Build and Scan Podman Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Podman
        run: |
          sudo apt update
          sudo apt install -y podman

      - name: Build Podman Image
        run: |
          podman build -t python-podman-app:latest .

  scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install Podman
        run: |
          sudo apt update
          sudo apt install -y podman

      - name: Install Trivy
        run: |
          sudo apt install -y wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.49.1_Linux-64bit.tar.gz
          tar -xvf trivy_0.49.1_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/

      - name: Scan Podman Image with Trivy
        run: |
          trivy image python-podman-app:latest




        

