name: Docker Build and Scan with Trivy (Podman)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Podman
        run: |
          sudo apt update
          sudo apt install -y podman

      - name: Build Docker Image using Podman
        run: |
          podman build -t python-docker-app:latest .
      
      - name: Install Trivy
        run: |
          sudo apt install -y wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_Linux-64bit.tar.gz
          tar -xvf trivy_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/

      - name: Scan Docker Image with Trivy
        run: |
          trivy image python-docker-app:latest

        

