name: Docker Build and Scan with Trivy (Podman)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Podman
        run: |
          sudo apt update
          sudo apt install -y podman

      - name: Configure Podman
        run: |
          mkdir -p $HOME/.config/containers
          echo -e "[engine]\ncgroup_manager = \"cgroupfs\"\nevents_logger = \"file\"" > $HOME/.config/containers/containers.conf
          systemctl --user enable --now podman

      - name: Build Docker Image using Podman
        run: |
          podman build -t python-docker-app:latest .

      - name: Install Trivy
        run: |
          sudo apt update
          sudo apt install -y wget curl
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh
          sudo mv trivy /usr/local/bin/
          echo "PATH=$PATH:/usr/local/bin" >> $GITHUB_ENV
          trivy --version  # Verify installation

      - name: Scan Docker Image with Trivy
        run: |
          trivy image python-docker-app:latest


        

